clean:
	# find . -type d -name "node_modules" -exec rm -rf {} +
	find . -type d -name "dist" -exec rm -rf {} +
	@echo "clean done"

check: 
	npm run lint
	npm run type-check
	npm run format

install:
	npm i

run:
	npm run dev