[environment]
python-version = "3.12"

[src]
include = ["src", "tests"]

[rules]
possibly-missing-import = "error"
invalid-argument-type = "error"
invalid-return-type = "error"
invalid-assignment = "error"
possibly-missing-attribute = "error"

unresolved-attribute = "warn"
unused-ignore-comment = "warn"
ignore-comment-unknown-rule = "warn"

invalid-declaration = "error"
