/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/health': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Health */
        get: operations['health_health_get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/categories/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Categories */
        get: operations['get_categories_categories__get']
        put?: never
        /** Create Category */
        post: operations['create_category_categories__post']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/categories/{category_id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Category */
        get: operations['get_category_categories__category_id__get']
        /** Update Category */
        put: operations['update_category_categories__category_id__put']
        post?: never
        /** Delete Category */
        delete: operations['delete_category_categories__category_id__delete']
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/shopping-lists/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Shopping Lists */
        get: operations['get_shopping_lists_shopping_lists__get']
        put?: never
        /** Create Shopping List */
        post: operations['create_shopping_list_shopping_lists__post']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/shopping-lists/{list_id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Shopping List */
        get: operations['get_shopping_list_shopping_lists__list_id__get']
        /** Update Shopping List */
        put: operations['update_shopping_list_shopping_lists__list_id__put']
        post?: never
        /** Delete Shopping List */
        delete: operations['delete_shopping_list_shopping_lists__list_id__delete']
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/shopping-lists/{list_id}/items/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Items */
        get: operations['get_items_shopping_lists__list_id__items__get']
        put?: never
        /** Create Item */
        post: operations['create_item_shopping_lists__list_id__items__post']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/shopping-lists/{list_id}/items/{item_id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Get Item */
        get: operations['get_item_shopping_lists__list_id__items__item_id__get']
        /** Update Item */
        put: operations['update_item_shopping_lists__list_id__items__item_id__put']
        post?: never
        /** Delete Item */
        delete: operations['delete_item_shopping_lists__list_id__items__item_id__delete']
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** Root */
        get: operations['root__get']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        /** CategoryCreate */
        CategoryCreate: {
            /** Name */
            name: string
            /** Color */
            color?: string | null
            /** Icon */
            icon?: string | null
        }
        /** CategoryResponse */
        CategoryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string
            /** Name */
            name: string
            /** Color */
            color?: string | null
            /** Icon */
            icon?: string | null
        }
        /** CategoryUpdate */
        CategoryUpdate: {
            /** Name */
            name: string
            /** Color */
            color?: string | null
            /** Icon */
            icon?: string | null
        }
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components['schemas']['ValidationError'][]
        }
        /** ItemCreate */
        ItemCreate: {
            /** Name */
            name: string
            /**
             * Quantity
             * @default 1
             */
            quantity: number
            /** Category Id */
            category_id?: string | null
        }
        /** ItemResponse */
        ItemResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string
            /** Name */
            name: string
            /** Quantity */
            quantity: number
            /** Is Checked */
            is_checked: boolean
            /**
             * Shopping List Id
             * Format: uuid
             */
            shopping_list_id: string
            /** Category Id */
            category_id?: string | null
            /**
             * Created At
             * Format: date-time
             */
            created_at: string
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string
        }
        /** ItemUpdate */
        ItemUpdate: {
            /** Name */
            name: string
            /**
             * Quantity
             * @default 1
             */
            quantity: number
            /**
             * Is Checked
             * @default false
             */
            is_checked: boolean
            /** Category Id */
            category_id?: string | null
        }
        /** ShoppingListCreate */
        ShoppingListCreate: {
            /** Name */
            name: string
            /** Description */
            description?: string | null
        }
        /** ShoppingListResponse */
        ShoppingListResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string
            /** Name */
            name: string
            /** Description */
            description?: string | null
            /**
             * Created At
             * Format: date-time
             */
            created_at: string
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string
        }
        /** ShoppingListUpdate */
        ShoppingListUpdate: {
            /** Name */
            name: string
            /** Description */
            description?: string | null
        }
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[]
            /** Message */
            msg: string
            /** Error Type */
            type: string
            /** Input */
            input?: unknown
            /** Context */
            ctx?: Record<string, never>
        }
    }
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    health_health_get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': unknown
                }
            }
        }
    }
    get_categories_categories__get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['CategoryResponse'][]
                }
            }
        }
    }
    create_category_categories__post: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': components['schemas']['CategoryCreate']
            }
        }
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['CategoryResponse']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_category_categories__category_id__get: {
        parameters: {
            query?: never
            header?: never
            path: {
                category_id: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['CategoryResponse']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    update_category_categories__category_id__put: {
        parameters: {
            query?: never
            header?: never
            path: {
                category_id: string
            }
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': components['schemas']['CategoryUpdate']
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['CategoryResponse']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    delete_category_categories__category_id__delete: {
        parameters: {
            query?: never
            header?: never
            path: {
                category_id: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_shopping_lists_shopping_lists__get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['ShoppingListResponse'][]
                }
            }
        }
    }
    create_shopping_list_shopping_lists__post: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': components['schemas']['ShoppingListCreate']
            }
        }
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['ShoppingListResponse']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_shopping_list_shopping_lists__list_id__get: {
        parameters: {
            query?: never
            header?: never
            path: {
                list_id: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['ShoppingListResponse']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    update_shopping_list_shopping_lists__list_id__put: {
        parameters: {
            query?: never
            header?: never
            path: {
                list_id: string
            }
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': components['schemas']['ShoppingListUpdate']
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['ShoppingListResponse']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    delete_shopping_list_shopping_lists__list_id__delete: {
        parameters: {
            query?: never
            header?: never
            path: {
                list_id: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_items_shopping_lists__list_id__items__get: {
        parameters: {
            query?: never
            header?: never
            path: {
                list_id: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['ItemResponse'][]
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    create_item_shopping_lists__list_id__items__post: {
        parameters: {
            query?: never
            header?: never
            path: {
                list_id: string
            }
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': components['schemas']['ItemCreate']
            }
        }
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['ItemResponse']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    get_item_shopping_lists__list_id__items__item_id__get: {
        parameters: {
            query?: never
            header?: never
            path: {
                item_id: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['ItemResponse']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    update_item_shopping_lists__list_id__items__item_id__put: {
        parameters: {
            query?: never
            header?: never
            path: {
                item_id: string
            }
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': components['schemas']['ItemUpdate']
            }
        }
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['ItemResponse']
                }
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    delete_item_shopping_lists__list_id__items__item_id__delete: {
        parameters: {
            query?: never
            header?: never
            path: {
                item_id: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['HTTPValidationError']
                }
            }
        }
    }
    root__get: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': unknown
                }
            }
        }
    }
}
