name: frontend

on:
  workflow_dispatch:
  push:
    branches: [development]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    branches: [development]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

permissions:
  contents: read

defaults:
  run:
    working-directory: frontend
    

jobs:
  frontend-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - uses: extractions/setup-just@v3

      - name: Install dependencies
        run: just clean-install

      - name: Run checks
        run: just check
